#ifndef CBEFF_QUALITY_ALGORITHM_IDENTIFIERS_H_INCLUDED
#define CBEFF_QUALITY_ALGORITHM_IDENTIFIERS_H_INCLUDED

#include <Core/NTypes.h>

#ifdef N_CPP
extern "C"
{
#endif

#define CBEFF_QAI_INTECH_QM 0x001A

#define CBEFF_QAI_NIST_NFIQ 0x377D

#define CBEFF_QAI_VENDOR_UNKNOWN_PRODUCT_UNKNOWN 0x0001

#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_1  0x0001
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_2  0x0002
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_3  0x0003
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_4  0x0004
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_5  0x0005
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_6  0x0006
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_7  0x0007
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_8  0x0008
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_9  0x0009
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_10 0x000A
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_11 0x000B
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_12 0x000C
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_13 0x000D
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_14 0x000E
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_15 0x000F
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_16 0x0010
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_17 0x0011
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_18 0x0012
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_19 0x0013
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_20 0x0014
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_21 0x0015
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_22 0x0016
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_23 0x0017
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_24 0x0018
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_25 0x0019
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_26 0x001A
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_27 0x001B
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_28 0x001C
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_29 0x001D
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_30 0x001E
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_31 0x001F
#define CBEFF_QAI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_QUALITY_METRIC_32 0x0020

#define CBEFF_QAI_NEUROTECHNOLOGY_FRQ_1 0x0100 // deprecated, use CBEFF_QAI_NEUROTECHNOLOGY_FINGER_RECORD_QUALITY_1 instead
#define CBEFF_QAI_NEUROTECHNOLOGY_FRQ_2 0x0101 // deprecated, use CBEFF_QAI_NEUROTECHNOLOGY_FINGER_RECORD_QUALITY_2 instead
#define CBEFF_QAI_NEUROTECHNOLOGY_FINGER_RECORD_QUALITY_1       0x0100
#define CBEFF_QAI_NEUROTECHNOLOGY_FINGER_RECORD_QUALITY_2       0x0101
#define CBEFF_QAI_NEUROTECHNOLOGY_FINGER_RECORD_QUALITY_3       0x0102
#define CBEFF_QAI_NEUROTECHNOLOGY_FINGER_RECORD_QUALITY_4       0x0103
#define CBEFF_QAI_NEUROTECHNOLOGY_FINGER_LIGHT_RECORD_QUALITY_1 0x0200
#define CBEFF_QAI_NEUROTECHNOLOGY_FACE_RECORD_QUALITY_1         0x0300
#define CBEFF_QAI_NEUROTECHNOLOGY_FACE_LIGHT_RECORD_QUALITY_1   0x0400
#define CBEFF_QAI_NEUROTECHNOLOGY_IRIS_RECORD_QUALITY_1         0x0500
#define CBEFF_QAI_NEUROTECHNOLOGY_IRIS_LIGHT_RECORD_QUALITY_1   0x0600

N_DECLARE_STATIC_OBJECT_TYPE(CbeffQualityAlgorithmIdentifiers)

#if defined(N_MSVC) && !defined(CBEFF_QUALITY_ALGORITHM_IDENTIFIERS_HPP_INCLUDED)
	#pragma deprecated("CBEFF_QAI_NEUROTECHNOLOGY_FRQ_1")
	#pragma deprecated("CBEFF_QAI_NEUROTECHNOLOGY_FRQ_2")
#endif

#ifdef N_CPP
}
#endif

#endif // !CBEFF_QUALITY_ALGORITHM_IDENTIFIERS_H_INCLUDED
